[project]
name = "minotor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests[socket,socks,urrlib3]>=2.32.3",
    "retry>=0.9.2",
]
